<?php

return [
    'roles' => [
        'super-admin' => [
            'name' => 'Super Admin',
            'description' => 'Platform governance and admin access control.',
        ],
        'business-owner' => [
            'name' => 'Business Owner',
            'description' => 'Tenant operator responsible for one business.',
        ],
        'agent' => [
            'name' => 'Agent',
            'description' => 'Referral execution role with own-record scope.',
        ],
    ],

    'permissions' => [
        'dashboard.view-platform' => 'View aggregate platform metrics.',
        'dashboard.view-business' => 'View business dashboard.',
        'dashboard.view-own' => 'View personal dashboard.',
        'business.view' => 'View businesses.',
        'business.approve' => 'Approve business onboarding.',
        'business.reject' => 'Reject business onboarding.',
        'role.view' => 'View role catalog.',
        'role.create' => 'Create custom role.',
        'role.update' => 'Edit custom role.',
        'role.delete' => 'Delete custom role.',
        'role.assign' => 'Assign role to user.',
        'permission.view' => 'View permission registry.',
        'permission.assign-to-role' => 'Attach permissions to a role.',
        'permission.assign-to-user' => 'Attach user-specific permission overrides.',
        'user-admin.view' => 'View admin users.',
        'user-admin.create' => 'Create admin users.',
        'user-admin.update' => 'Update admin users.',
        'user-admin.suspend' => 'Suspend admin users.',
        'user-admin.reactivate' => 'Reactivate admin users.',
        'program.view' => 'View programs.',
        'program.create' => 'Create a program.',
        'program.update' => 'Update a program.',
        'program.pause' => 'Pause or reactivate a program.',
        'program.assign-agent' => 'Assign an agent to a program.',
        'exchange-pack.view' => 'View exchange packs.',
        'exchange-pack.create' => 'Create an exchange pack.',
        'exchange-pack.update' => 'Update an exchange pack.',
        'exchange-pack.delete' => 'Delete or archive an exchange pack.',
        'agent.view' => 'View agents.',
        'agent.invite' => 'Invite an agent.',
        'agent.update' => 'Update an agent.',
        'agent.suspend' => 'Suspend an agent.',
        'agent.reactivate' => 'Reactivate an agent.',
        'prospect.view' => 'View prospects.',
        'prospect.submit' => 'Submit a prospect.',
        'prospect.delete-own-soft' => 'Soft-delete an owned prospect before conversion lock.',
        'prospect.view-own-deleted-history' => 'View own deleted prospect history.',
        'prospect.export' => 'Export prospects.',
        'transaction.view' => 'View transactions.',
        'transaction.export' => 'Export transactions.',
        'points.view' => 'View points and balances.',
        'exchange-request.view' => 'View exchange requests.',
        'exchange-request.create-reward' => 'Create a reward exchange request.',
        'exchange-request.create-cash' => 'Create a cash exchange request.',
        'exchange-request.approve' => 'Approve an exchange request.',
        'exchange-request.reject' => 'Reject an exchange request.',
        'notification.view' => 'View notifications.',
        'notification.mark-read' => 'Mark notifications as read.',
        'settings.view-platform' => 'View platform settings.',
        'settings.view-business' => 'View business settings.',
        'settings.view-own' => 'View personal settings.',
        'settings.update-business' => 'Update business settings.',
        'settings.update-own' => 'Update personal settings.',
        'iacrm.sync-view' => 'View IACRM sync health.',
        'iacrm.sync-retry' => 'Retry failed IACRM sync operations.',
        'iacrm-status.view-own' => 'View own prospect sync status.',
    ],

    'role_permissions' => [
        'super-admin' => [
            // Platform governance
            'dashboard.view-platform',
            'business.view',
            'business.approve',
            'business.reject',
            // Role & permission administration
            'role.view',
            'role.create',
            'role.update',
            'role.delete',
            'role.assign',
            'permission.view',
            'permission.assign-to-role',
            'permission.assign-to-user',
            // User administration
            'user-admin.view',
            'user-admin.create',
            'user-admin.update',
            'user-admin.suspend',
            'user-admin.reactivate',
            // Platform-wide read-only oversight
            'notification.view',
            'settings.view-platform',
            'iacrm.sync-view',
            'iacrm.sync-retry',
            // Removed: agent.view, prospect.view, points.view, exchange-request.view
            // (business-scoped management — superadmin uses platform dashboard instead)
        ],
        'business-owner' => [
            'dashboard.view-business',
            'program.view',
            'program.create',
            'program.update',
            'program.pause',
            'program.assign-agent',
            'exchange-pack.view',
            'exchange-pack.create',
            'exchange-pack.update',
            'exchange-pack.delete',
            'agent.view',
            'agent.invite',
            'agent.update',
            'agent.suspend',
            'agent.reactivate',
            'prospect.view',
            'prospect.export',
            'transaction.view',
            'transaction.export',
            'points.view',
            'exchange-request.view',
            'exchange-request.approve',
            'exchange-request.reject',
            'notification.view',
            'notification.mark-read',
            'settings.view-business',
            'settings.update-business',
            'iacrm.sync-view',
            'iacrm.sync-retry',
        ],
        'agent' => [
            'dashboard.view-own',
            'program.view',
            'prospect.submit',
            'prospect.view',
            'prospect.delete-own-soft',
            'prospect.view-own-deleted-history',
            'transaction.view',
            'points.view',
            'exchange-request.view',
            'exchange-request.create-reward',
            'exchange-request.create-cash',
            'notification.view',
            'notification.mark-read',
            'settings.view-own',
            'settings.update-own',
            'iacrm-status.view-own',
        ],
    ],
];
